### ISSUE TITLE
Tool Bar Icon

### ISSUE THREAD

**Issue by smaragdus** [ktr0731/excl#1]
On dark themes (such as for example [Oceanic](https://chrome.google.com/webstore/detail/oceanic/gbbacdmgjdfajabgglpjifcedoajdimg)) the tool bar button of [excl](https://github.com/ktr0731/excl) is almost invisible in the tool bar, screen:

![excl 0 1 1 - 2020-01-18 - 003](https://user-images.githubusercontent.com/9025757/72652695-6fae7700-3990-11ea-903a-dc3ace27c452.png)

I would suggest that:

- either **excl** detects the theme colour and changes the tool bar button colour automatically;
- or  **excl** has options where the user can choose between light and dark button;

I suppose that the latter (option to select tool bar button colour) would be simpler and easier to implement.

Overall **excl** is a simple and nice extension that works well, it is just that the button is hard to see on dark themes.

**Comment by ktr0731** [comment]
Thanks for your feedback!
First, I changed the icon to a new one because it is the easiest way.
If it looks hard to see, I'll implement one of the ways you suggested :)

FYI: new icon with Oceanic theme
<img width="138" alt="スクリーンショット 2020-01-19 23 22 57" src="https://user-images.githubusercontent.com/12953836/72683197-8c75b680-3b18-11ea-995c-bbf94a033b56.png">

**Comment by smaragdus** [comment]
@ktr0731 

Thank you for the quick response, for the new button and for the screen shot,

> First, I changed the icon to a new one because it is the easiest way.

The new button looks nice on the screen shot above. However the [Chrome Web Store](https://chrome.google.com/webstore/detail/excl/gpdohcgeplmiakcbgdagnajcdjlogbnl) hasn't yet updated the extension- it is still at version **0.1.1**. As far as I know updates are manually reviewed and this slows down the update process. When I get the update through the store I will have a look. As a workaround I currently moved the button to the hidden part as the theme does not apply to it and the old button is well visible on white background. When I get the latest version of [excl](https://github.com/ktr0731/excl) I will have another look and will close this issue.

**Comment by smaragdus** [comment]
@ktr0731 

I got [excl](https://github.com/ktr0731/excl) updated to version 0.1.2 via [Chrome Web Store](https://chrome.google.com/webstore/detail/excl/gpdohcgeplmiakcbgdagnajcdjlogbnl) and I can confirm that the new tool bar button is pretty visible on dark themes, thanks!
